name: media_info_example
description: Demonstrates how to use the media_info plugin.
publish_to: 'none'

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  file_picker: ^1.3.2
  path_provider: ^0.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  media_info:
    path: ../

flutter:
  uses-material-design: true
