name: media_info
description: Determine multimedia file properties like width, height, duration
version: 0.5.2
author: Sebastian Roth <seb@ivity.asia>
homepage: https://github.com/ened/flutter_plugin_media_info

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  file_picker: ^1.4.3+2
  path_provider: ^1.5.1
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: asia.ivity.mediainfo
    pluginClass: MediaInfoPlugin
