name: media_info
description: Determine multimedia file properties like width, height, duration
version: 0.6.5
homepage: https://github.com/ened/flutter_plugin_media_info

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  mime: ^0.9.7
  flutter:
    sdk: flutter

dev_dependencies:
  file_picker: ^2.1.7
  path_provider: ^1.6.27
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: asia.ivity.mediainfo
        pluginClass: MediaInfoPlugin
      ios:
        pluginClass: IVMediaInfoPlugin
