name: media_info
description: Determine multimedia file properties like width, height, duration
version: 0.4.1
author: Sebastian Roth <seb@ivity.asia>
homepage: https://github.com/ened/flutter_plugin_media_info

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  file_picker: ^1.4.2
  path_provider: ^1.3.0

flutter:
  plugin:
    androidPackage: asia.ivity.mediainfo
    pluginClass: MediaInfoPlugin
